// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZAR9FwfPrmNnbwkYSU4ao65St-0vzgA',
    appId: '1:658191778895:android:ce4ab2ad0618c42b17d63a',
    messagingSenderId: '658191778895',
    projectId: 'ai-pantry-my-86ad3',
    databaseURL: 'https://ai-pantry-my-86ad3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-pantry-my-86ad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGb8Y-MbwIRkYSDQ0jeBYcHAtb55WGq5I',
    appId: '1:658191778895:ios:5bb6727e36e5198817d63a',
    messagingSenderId: '658191778895',
    projectId: 'ai-pantry-my-86ad3',
    databaseURL: 'https://ai-pantry-my-86ad3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-pantry-my-86ad3.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
